### PR TITLE
Modernize project

### PR DESCRIPTION
**Pull request by res0nance**
Bring project more inline with the current version of Jenkins

### CODE REVIEW

**Comment by res0nance** [comment]
Addressed both comments

**Comment by dagwieers** [comment]
What is needed to get this merged?

**Comment by jglick** [comment]
https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by sugonyak** [comment]
Merged. Sorry for slow response.

**Comment by dagwieers** [comment]
@sugonyak Thanks !

**Comment by dagwieers** [comment]
@sugonyak This hasn't been released and I opened a JIRA ticket for a release which has gone unnoticed.
https://issues.jenkins-ci.org/browse/JENKINS-63020

**Comment by res0nance** [comment]
This seems to have been released according to https://plugins.jenkins.io/build-with-parameters/

**Comment by dagwieers** [comment]
Ok, I missed this. Thanks !

**Pull request merged**
