### PR TITLE
[JENKINS-35378] Support for pipelines

### PR DESCRIPTION
**Pull request by tbekas**
WorkflowJobs are not a subtype of AbstractProject so they were omitted.

### CODE REVIEW

**Comment by kevinroisin** [comment]
Is this support in a released version of the plugin? It looks like version 1.3 was last released on Nov 09, 2014 per https://wiki.jenkins-ci.org/display/JENKINS/Build+With+Parameters+Plugin.

**Comment by Jimilian** [comment]
You can download it from https://jenkins.ci.cloudbees.com/job/plugins/job/build-with-parameters-plugin/15/org.jenkins-ci.plugins$build-with-parameters/ and install via `Install Plugin` -> `Advanced` panel

**Comment by KamilKopaczyk** [comment]
Is there any reason why this fix is not available in jenkins plugin manager?

**Comment by sugonyakivan** [comment]
Because no one yet published updated plugin to Jenkins.

**Comment by KamilKopaczyk** [comment]
According to what i read at https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins, only plugin author (so jessicaaustin in this case) can publish new version of plugin. Correct?

**Comment by harveyr** [comment]
@jessicaaustin Is this something that's easy to do? I'd love to use this, but I'll never be able to convince my ops friends to install it the manual way.

**Comment by jessicaaustin** [comment]
I'm actually no longer actively maintaining this plugin.

[According to the wiki](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Requestuploadpermissions), it looks like the permissions to push a new version are set here:

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-build-with-parameters.yml

If someone wants to be added as a developer there and push a new release, please let me know and I can add you to the yaml file. 

@sugonyakivan I'll go ahead and add permissions for you since we talked about adding you as a maintainer.

**Comment by sugonyakivan** [comment]
Prepping for release now. Hoping to publish it in few hours.

**Pull request merged**
